---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.transaction-persistence-service}
    password: ${spring.datasource.password.transaction-persistence-service}
    url: ${spring.datasource.url.transaction-persistence-service}


logging:
  config: ${backbase.config.dir}/transaction-persistence-service/logback.xml
