alter table TB_IMPORT_PROCESS_LOGS
    ADD CREATOR_USERNAME varchar(255);

alter table TB_IMPORT_PROCESS_LOGS ADD COLUMN TMP_MESSAGE clob;

UPDATE TB_IMPORT_PROCESS_LOGS SET TMP_MESSAGE = MESSAGE;

COMMIT;

alter table TB_IMPORT_PROCESS_LOGS DROP COLUMN MESSAGE;

alter table TB_IMPORT_PROCESS_LOGS RENAME COLUMN TMP_MESSAGE TO MESSAGE;

COMMIT;