create table CANCEL_IMPORT (
    id number(19,0) not null,
    cancelled nvarchar2(10),
    primary key (id)
);

CREATE SEQUENCE "CANCEL_IMPORT_SEQ"
INCREMENT BY 1
MAXVALUE 9999999999999999999999999999
START WITH 1
CACHE 20
NOORDER
NOCYCLE;

CREATE OR REPLACE TRIGGER "CANCEL_IMPORT_ID"
BEFORE INSERT ON CANCEL_IMPORT
FOR EACH ROW
  BEGIN
    SELECT
      CANCEL_IMPORT_SEQ.NEXTVAL
    INTO :new.id
    FROM dual;
  END;
/