---
### Live profile
spring:
  profiles: live
#  datasource:
#    driver-class-name: ${spring.datasource.driver-class-name}
#    username: ${spring.datasource.username.contact-presentation-service}
#    password: ${spring.datasource.password.contact-presentation-service}
#    url: ${spring.datasource.url.contact-presentation-service}

logging:
  config: ${backbase.config.dir}/contact-presentation-service/logback.xml

# Contact Extensions Example
backbase:
  api:
    extensions:
      classes:
        com.backbase.presentation.contact.rest.spec.v2.contacts.ContactsGetResponseBody: pokemon-data
        com.backbase.presentation.contact.rest.spec.v2.contacts.ContactsPostRequestBody: pokemon-data
        com.backbase.presentation.contact.rest.spec.v2.contacts.ContactPutRequestBody: pokemon-data
        com.backbase.pandp.party.command.rest.spec.v1.party.PartiesGetResposeBody: pokemon-data
        com.backbase.pandp.party.command.rest.spec.v1.party.PartiesPostRequestBody: pokemon-data
        com.backbase.pandp.party.command.rest.spec.v1.party.PartiesPutRequestBody: pokemon-data
        com.backbase.pandp.party.command.event.spec.v1.Party: pokemon-data
      property-sets:
        pokemon-data:
          properties:
          - property-name: favPokemon
            security:
              - confidential
            type: string
          - property-name: rank
            security:
              - confidential
            type: number
  persistence:
    enabled: false
  contact:
    audit:
      enabled: false