---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.messages-pandp-service}
    password: ${spring.datasource.password.messages-pandp-service}
    url: ${spring.datasource.url.messages-pandp-service}

logging:
  config: ${backbase.config.dir}/messages-pandp-service/logback.xml
