---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.party-pandp-service}
    password: ${spring.datasource.password.party-pandp-service}
    url: ${spring.datasource.url.party-pandp-service}

logging:
  config: ${backbase.config.dir}/party-pandp-service/logback.xml

# Contact Extensions Example
backbase:
  api:
    extensions:
      classes:
        com.backbase.pandp.party.command.event.spec.v1.Party: pokemon-data
        com.backbase.pandp.party.persistence.Party: pokemon-data
      property-sets:
        pokemon-data:
          properties:
          - property-name: favPokemon
            security:
              - confidential
            type: string
          - property-name: rank
            security:
              - confidential
            type: number